<?php // generated by https://www.devsense.com/

/**
 * Determine if a variable is considered set, this means if a variable is declared and is different than `null` .
 *
 * @param mixed $var The variable to be checked.
 * @param mixed $vars Further variables.
 * @return bool Returns `true` if `var` exists and has any value other than `null` . `false` otherwise.
 */

function savePhoto($file) {
    $targetDir = "uploads/";
    $targetFile = $targetDir . basename($file["name"]);
    $uploadOk = 1;
    $imageFileType = strtolower(pathinfo($targetFile, PATHINFO_EXTENSION));

    // Periksa apakah file adalah gambar asli atau tidak
    $check = getimagesize($file["tmp_name"]);
    if($check !== false) {
        echo "File adalah gambar - " . $check["mime"] . ".";
        $uploadOk = 1;
    } else {
        echo "File bukan gambar.";
        $uploadOk = 0;
    }

    // Periksa apakah file sudah ada
    if (file_exists($targetFile)) {
        echo "Maaf, file sudah ada.";
        $uploadOk = 0;
    }

    // Periksa ukuran file (misalnya maksimal 5MB)
    if ($file["size"] > 5000000) {
        echo "Maaf, file Anda terlalu besar.";
        $uploadOk = 0;
    }

    // Hanya izinkan format file gambar tertentu
    if($imageFileType != "jpg" && $imageFileType != "png" && $imageFileType != "jpeg"
    && $imageFileType != "gif" ) {
        echo "Maaf, hanya file JPG, JPEG, PNG & GIF yang diperbolehkan.";
        $uploadOk = 0;
    }

    // Periksa apakah $uploadOk adalah 0 karena kesalahan
    if ($uploadOk == 0) {
        echo "Maaf, file Anda tidak diunggah.";
    // Jika semuanya baik-baik saja, coba unggah file
    } else {
        if (move_uploaded_file($file["tmp_name"], $targetFile)) {
            echo "File ". basename($file["name"]). " telah berhasil diunggah.";
        } else {
            echo "Maaf, terjadi kesalahan saat mengunggah file Anda.";
        }
    }
}

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    if (isset($_FILES["photo"])) {
        savePhoto($_FILES["photo"]);
    } else {
        echo "Tidak ada file yang diunggah.";
    }
}
?>